# Generated by Django 6.0.3 on 2026-04-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cancel_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_paid_delivery',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='is_first_order_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shopkeeper_paid_delivery',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
