# Generated by Django 6.0.3 on 2026-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer_paid_delivery_order_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
