# Generated by Django 6.0.3 on 2026-04-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('ready', 'Ready for Pickup'), ('assigned', 'Delivery Assigned'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returning_to_store', 'Returning to Store'), ('returned_to_store', 'Returned to Store'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
