# Generated by Django 6.0.3 on 2026-05-22 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
        ('stores', '0010_alter_store_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status', 'created_at'], name='orders_orde_store_i_f84db8_idx'),
        ),
    ]
