# Generated by Django 6.0.3 on 2026-04-26 17:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        ('services', '0002_booking_customer_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='vehicle_details',
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='services.booking'),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='task_type',
            field=models.CharField(choices=[('order_delivery', 'Product Order Delivery'), ('service_pickup', 'Service Item Pickup from Customer'), ('service_return', 'Service Item Return to Customer')], default='order_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'delivery'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
