# Generated by Django 6.0.3 on 2026-05-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_deliveryassignment_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='task_type',
            field=models.CharField(choices=[('order_delivery', 'Product Order Delivery'), ('service_pickup', 'Service Item Pickup from Customer'), ('service_return', 'Service Item Return to Customer')], db_index=True, default='order_delivery', max_length=20),
        ),
    ]
