# Generated by Django 6.0.3 on 2026-04-26 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Confirmed', 'Confirmed'), ('ReadyForPickup', 'Ready for Pickup from Customer'), ('Assigned', 'Delivery Assigned'), ('PickedUp', 'Picked Up from Customer'), ('ArrivedAtStore', 'Arrived at Store'), ('ServiceInProgress', 'Service in Progress'), ('ReadyForReturn', 'Ready for Return to Customer'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
