# Generated by Django 6.0.3 on 2026-04-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_booking_cancel_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
