# Generated by Django 6.0.3 on 2026-05-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_booking_customer_address_booking_customer_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Confirmed', 'Confirmed'), ('ReadyForPickup', 'Ready for Pickup from Customer'), ('Assigned', 'Delivery Assigned'), ('PickedUp', 'Picked Up from Customer'), ('ArrivedAtStore', 'Arrived at Store'), ('ServiceInProgress', 'Service in Progress'), ('ReadyForReturn', 'Ready for Return to Customer'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
