# Generated by Django 6.0.3 on 2026-05-22 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_booking_status_alter_service_is_active'),
        ('stores', '0010_alter_store_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['store', 'status', 'created_at'], name='services_bo_store_i_049985_idx'),
        ),
    ]
