# Generated by Django 6.0.3 on 2026-04-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_store_image_store_contact_name_store_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
