# Generated by Django 6.0.3 on 2026-04-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_address_store_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_products',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='has_services',
            field=models.BooleanField(default=False),
        ),
    ]
