# Generated by Django 6.0.3 on 2026-04-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
