# Generated by Django 6.0.3 on 2026-04-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='first_order_free_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='max_free_delivery_cap',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
