# Generated by Django 6.0.3 on 2026-04-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
