# Generated by Django 6.0.3 on 2026-04-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_order',
            field=models.BooleanField(default=True),
        ),
    ]
